const PERMISSIONS = {
  "TEST": "TEST",
  "COLOREDITOR": "COLOREDITOR",
  "NOTIFICATION_BELL": "NOTIFICATION_BELL",
  "LOGOUT":"LOGOUT",
  "GARBAGE":"GARBAGE",
  "PROFILE":"PROFILE",
  "REPORTS":"REPORTS",
  "SHARED_WITH_ME":"SHARED_WITH_ME",
  "COLLECTIONS":"COLLECTIONS",
  "CREATOR":"CREATOR",
  "CREATE_COLLECTION":"CREATE_COLLECTION",
  "CREATE_ATLAS":"CREATE_ATLAS",
  "CREATE_REPORT":"CREATE_REPORT",
  "CREATE_DATA":"CREATE_DATA",
  "ADMIN_PERMISSIONS":"ADMIN_PERMISSIONS",
  "ADMIN_ROLES":"ADMIN_ROLES",
  "ADMIN_TAGS":"ADMIN_TAGS",
  "ADMIN":"ADMIN",
  "SIGNUP":"SIGNUP",
  "VIEW_APPLICATION":"VIEW_APPLICATION",
  "PAYMENT_SETTINGS":"PAYMENT_SETTINGS"
}

export { PERMISSIONS };
