/**
 * Everything a user can do is done via a permission
 * Permission naming conventions
 * IDENTIFIER + ACTION
 * IDENTIFIER = {(COMPONENT||PAGE||CONTROLLER)}
 * concat with _
 * COMPONENT||PAGE -> look at angular structure
 * ACTION:
 *    VIEW -> SEEING STUFF
 *    EDIT -> CREATE UPDATE DELETE
 *    ADMIN -> CHANGE SYSTEM BEHAVIOUR
 *    CHOOSE -> ..
 *    SAVE -> ...
 */

const PERMISSIONS = {
  PLATFORM_VIEW: 'PLATFORM_VIEW',
  LOGOUT_VIEW: 'LOGOUT_VIEW',
  GARBAGE_VIEW: 'GARBAGE_VIEW',
  PROFILE_VIEW: 'PROFILE_VIEW',
  MYREPORTS_VIEW: 'MYREPORTS_VIEW',
  SHAREDWITHME_VIEW: 'SHAREDWITHME_VIEW',
  COLLECTIONS_VIEW: 'COLLECTIONS_VIEW',
  SIGNUP_VIEW: 'SIGNUP_VIEW',
  PAYMENT_VIEW: 'PAYMENT_VIEW',
  PAYMENT_SETTINGS: 'PAYMENT_SETTINGS',
  NOTIFICATION_VIEW: 'NOTIFICATION_VIEW',
  CREATOR_VIEW: 'CREATOR_VIEW', //is the plus shown in the header

  COLLECTION_CREATE: 'COLLECTION_CREATE',
  ATLAS_CREATE: 'ATLAS_CREATE',
  REPORT_CREATE: 'REPORT_CREATE',
  DATA_CREATE: 'DATA_CREATE',
  CONTENT_SAVE: 'CONTENT_SAVE',
  CONTENT_DOWNLOAD_SVG: 'CONTENT_DOWNLOAD_SVG',
  CONTENT_DOWNLOAD_GEOJSON: 'CONTENT_DOWNLOAD_GEOJSON',
  CONTENT_DOWNLOAD_PNG: 'CONTENT_DOWNLOAD_PNG',
  CONTENT_DOWNLOAD_CSV: 'CONTENT_DOWNLOAD_CSV',
  CONTENT_DOWNLOAD_XLS: 'CONTENT_DOWNLOAD_XLS',
  TEMPLATES_VIEW: 'TEMPLATES_VIEW',
  TEMPLATES_EDIT: 'TEMPLATES_EDIT',
  LAYOUT_VIEW: 'LAYOUT_VIEW',
  LAYOUT_EDIT: 'LAYOUT_EDIT',
  MAP_LAYER_VIEW: 'MAP_LAYER_VIEW',
  MAP_LAYER_EDIT: 'MAP_LAYER_EDIT',
  ADVANCED_TOOLTIP_ADDIMAGESFROMDATA: 'ADVANCED_TOOLTIP_ADDIMAGESFROMDATA',
  ADVANCED_TOOLTIP_ADDLINKSFROMDATA: 'ADVANCED_TOOLTIP_ADDLINKSFROMDATA',
  DESCRIPTION_ADDVALUEFROMDATA: 'DESCRIPTION_ADDVALUEFROMDATA',
  COPY_SLUG: 'COPY_SLUG',
  EMBED: 'EMBED',
  APPLY_UPDATE: 'APPLY_UPDATE',
  CONTENT_REUSAGE: 'CONTENT_REUSAGE',

  COLOREDITOR_VIEW: 'COLOREDITOR_VIEW',
  COLOREDITOR_EDIT: 'COLOREDITOR_EDIT',
  SMARTFUNCTIONS_VIEW: 'SMARTFUNCTIONS_VIEW',
  CONTENT_PRIVATE: 'CONTENT_PRIVATE',
  CONTENT_LINKSHARE: 'CONTENT_LINKSHARE',
  LOGO_UPLOAD: 'LOGO_UPLOAD',
  LOGO_EDIT: 'LOGO_EDIT',

  USERMANAGEMENT_VIEW: 'USERMANAGEMENT_VIEW',
  USERMANAGEMENT_EDIT: 'USERMANAGEMENT_EDIT',
  TAGMANAGEMENT_VIEW: 'TAGMANAGEMENT_VIEW',
  TAGMANAGEMENT_EDIT: 'TAGMANAGEMENT_EDIT',
  TAG_VIEW: 'TAG_VIEW',

  SLA: 'SLA',
  API: 'API'
};

/*
const PERMISSIONSBACKUP = {
  "TEST": "TEST",
  "COLOREDITOR": "COLOREDITOR",
  "NOTIFICATION_BELL": "NOTIFICATION_BELL",
  "LOGOUT":"LOGOUT",
  "GARBAGE":"GARBAGE",
  "PROFILE":"PROFILE",
  "REPORTS":"REPORTS",
  "SHARED_WITH_ME":"SHARED_WITH_ME",
  "COLLECTIONS":"COLLECTIONS",
  "CREATOR":"CREATOR",
  "CREATE_COLLECTION":"CREATE_COLLECTION",
  "CREATE_ATLAS":"CREATE_ATLAS",
  "CREATE_REPORT":"CREATE_REPORT",
  "CREATE_DATA":"CREATE_DATA",
  "ADMIN_PERMISSIONS":"ADMIN_PERMISSIONS",
  "ADMIN_ROLES":"ADMIN_ROLES",
  "ADMIN_TAGS":"ADMIN_TAGS",
  "ADMIN":"ADMIN",
  "SIGNUP":"SIGNUP",
  "VIEW_APPLICATION":"VIEW_APPLICATION",
  "PAYMENT_SETTINGS":"PAYMENT_SETTINGS"
}
*/

const ANON_USER = {
  id: '5d4858873a75ba001db8de2c',
  token:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZDQ4NTg4NzNhNzViYTAwMWRiOGRlMmMiLCJlbWFpbCI6ImFub25AMjNkZWdyZWVzLmlvIiwic2x1ZyI6ImFub255bW91cy0xIiwicm9sZXMiOlsiNWQ0OGFiYzU4MzE4NmMwMDFlZjZjNzhlIl0sImV4cCI6MTU5NjE4MDk3MCwiaWF0IjoxNTY1MDc2OTcwfQ.pvBKkmYcM4XjsOX-CfFSrngDX0nTzc8N2754kC0X0J0'
};

export { PERMISSIONS, ANON_USER };
